
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${ESTATE_DATASOURCE_URL}/ESTATE
    username: ${ESTATE_DATASOURCE_USERNAME}
    password: ${ESTATE_DATASOURCE_PASSWORD}
    initialization-mode: always

  profiles:
    active: dev


logging.level:
  kr.co.estate: DEBUG
  org.springframework.jdbc.core: DEBUG
  org.hibernate.type: TRACE
  org.hibernate.SQL: DEBUG